# Generated by Django 5.2.8 on 2025-11-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStick',
            new_name='countInStock',
        ),
    ]
